# ===================================
#  List Behavior Config
# ===================================

title: Manage Users
list: @/plugins/cnesmeteo/user/models/user/columns.yaml
modelClass: CNESmeteo\User\Models\User
recordUrl: cnesmeteo/user/users/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt



